name: API Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        run: sudo apt-get install jq -y

      - name: Run validation script for all users in CSV
        run: |
          for user_id in {1..10}
          do
            bash validate_data.sh $user_id
          done